//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_IngredientList_Ingredient", "Ingredient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataLayer.Ingredient), "IngredientList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataLayer.IngredientList), true)]
[assembly: EdmRelationshipAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_IngredientList_Measurement", "Measurement", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataLayer.Measurement), "IngredientList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataLayer.IngredientList), true)]
[assembly: EdmRelationshipAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_IngredientList_Recipe", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataLayer.Recipe), "IngredientList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataLayer.IngredientList), true)]
[assembly: EdmRelationshipAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_Directions_Recipe", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataLayer.Recipe), "Direction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataLayer.Direction), true)]

#endregion

namespace DataLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class db505e4eb8d47b40b7a6d7a05a001ba2a9Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new db505e4eb8d47b40b7a6d7a05a001ba2a9Entities object using the connection string found in the 'db505e4eb8d47b40b7a6d7a05a001ba2a9Entities' section of the application configuration file.
        /// </summary>
        public db505e4eb8d47b40b7a6d7a05a001ba2a9Entities() : base("name=db505e4eb8d47b40b7a6d7a05a001ba2a9Entities", "db505e4eb8d47b40b7a6d7a05a001ba2a9Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db505e4eb8d47b40b7a6d7a05a001ba2a9Entities object.
        /// </summary>
        public db505e4eb8d47b40b7a6d7a05a001ba2a9Entities(string connectionString) : base(connectionString, "db505e4eb8d47b40b7a6d7a05a001ba2a9Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new db505e4eb8d47b40b7a6d7a05a001ba2a9Entities object.
        /// </summary>
        public db505e4eb8d47b40b7a6d7a05a001ba2a9Entities(EntityConnection connection) : base(connection, "db505e4eb8d47b40b7a6d7a05a001ba2a9Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredient> Ingredients
        {
            get
            {
                if ((_Ingredients == null))
                {
                    _Ingredients = base.CreateObjectSet<Ingredient>("Ingredients");
                }
                return _Ingredients;
            }
        }
        private ObjectSet<Ingredient> _Ingredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IngredientList> IngredientLists
        {
            get
            {
                if ((_IngredientLists == null))
                {
                    _IngredientLists = base.CreateObjectSet<IngredientList>("IngredientLists");
                }
                return _IngredientLists;
            }
        }
        private ObjectSet<IngredientList> _IngredientLists;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Measurement> Measurements
        {
            get
            {
                if ((_Measurements == null))
                {
                    _Measurements = base.CreateObjectSet<Measurement>("Measurements");
                }
                return _Measurements;
            }
        }
        private ObjectSet<Measurement> _Measurements;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Recipe> Recipes
        {
            get
            {
                if ((_Recipes == null))
                {
                    _Recipes = base.CreateObjectSet<Recipe>("Recipes");
                }
                return _Recipes;
            }
        }
        private ObjectSet<Recipe> _Recipes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Direction> Directions
        {
            get
            {
                if ((_Directions == null))
                {
                    _Directions = base.CreateObjectSet<Direction>("Directions");
                }
                return _Directions;
            }
        }
        private ObjectSet<Direction> _Directions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients(Ingredient ingredient)
        {
            base.AddObject("Ingredients", ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IngredientLists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredientLists(IngredientList ingredientList)
        {
            base.AddObject("IngredientLists", ingredientList);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Measurements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeasurements(Measurement measurement)
        {
            base.AddObject("Measurements", measurement);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Recipes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipes(Recipe recipe)
        {
            base.AddObject("Recipes", recipe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Directions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDirections(Direction direction)
        {
            base.AddObject("Directions", direction);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db505e4eb8d47b40b7a6d7a05a001ba2a9Model", Name="Direction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Direction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Direction object.
        /// </summary>
        /// <param name="directionsId">Initial value of the DirectionsId property.</param>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="stepNumber">Initial value of the StepNumber property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static Direction CreateDirection(global::System.Int32 directionsId, global::System.Int32 recipeId, global::System.Int32 stepNumber, global::System.String text)
        {
            Direction direction = new Direction();
            direction.DirectionsId = directionsId;
            direction.RecipeId = recipeId;
            direction.StepNumber = stepNumber;
            direction.Text = text;
            return direction;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DirectionsId
        {
            get
            {
                return _DirectionsId;
            }
            set
            {
                if (_DirectionsId != value)
                {
                    OnDirectionsIdChanging(value);
                    ReportPropertyChanging("DirectionsId");
                    _DirectionsId = StructuralObject.SetValidValue(value, "DirectionsId");
                    ReportPropertyChanged("DirectionsId");
                    OnDirectionsIdChanged();
                }
            }
        }
        private global::System.Int32 _DirectionsId;
        partial void OnDirectionsIdChanging(global::System.Int32 value);
        partial void OnDirectionsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                OnRecipeIdChanging(value);
                ReportPropertyChanging("RecipeId");
                _RecipeId = StructuralObject.SetValidValue(value, "RecipeId");
                ReportPropertyChanged("RecipeId");
                OnRecipeIdChanged();
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StepNumber
        {
            get
            {
                return _StepNumber;
            }
            set
            {
                OnStepNumberChanging(value);
                ReportPropertyChanging("StepNumber");
                _StepNumber = StructuralObject.SetValidValue(value, "StepNumber");
                ReportPropertyChanged("StepNumber");
                OnStepNumberChanged();
            }
        }
        private global::System.Int32 _StepNumber;
        partial void OnStepNumberChanging(global::System.Int32 value);
        partial void OnStepNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false, "Text");
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_Directions_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_Directions_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_Directions_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_Directions_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_Directions_Recipe", "Recipe", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db505e4eb8d47b40b7a6d7a05a001ba2a9Model", Name="Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredient object.
        /// </summary>
        /// <param name="ingredientId">Initial value of the IngredientId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Ingredient CreateIngredient(global::System.Int32 ingredientId, global::System.String name)
        {
            Ingredient ingredient = new Ingredient();
            ingredient.IngredientId = ingredientId;
            ingredient.Name = name;
            return ingredient;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientId
        {
            get
            {
                return _IngredientId;
            }
            set
            {
                if (_IngredientId != value)
                {
                    OnIngredientIdChanging(value);
                    ReportPropertyChanging("IngredientId");
                    _IngredientId = StructuralObject.SetValidValue(value, "IngredientId");
                    ReportPropertyChanged("IngredientId");
                    OnIngredientIdChanged();
                }
            }
        }
        private global::System.Int32 _IngredientId;
        partial void OnIngredientIdChanging(global::System.Int32 value);
        partial void OnIngredientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_IngredientList_Ingredient", "IngredientList")]
        public EntityCollection<IngredientList> IngredientLists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<IngredientList>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Ingredient", "IngredientList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<IngredientList>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Ingredient", "IngredientList", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db505e4eb8d47b40b7a6d7a05a001ba2a9Model", Name="IngredientList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IngredientList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IngredientList object.
        /// </summary>
        /// <param name="ingredientListId">Initial value of the IngredientListId property.</param>
        /// <param name="ingredientId">Initial value of the IngredientId property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="measurementId">Initial value of the MeasurementId property.</param>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        public static IngredientList CreateIngredientList(global::System.Int32 ingredientListId, global::System.Int32 ingredientId, global::System.Int32 amount, global::System.Int32 measurementId, global::System.Int32 recipeId)
        {
            IngredientList ingredientList = new IngredientList();
            ingredientList.IngredientListId = ingredientListId;
            ingredientList.IngredientId = ingredientId;
            ingredientList.Amount = amount;
            ingredientList.MeasurementId = measurementId;
            ingredientList.RecipeId = recipeId;
            return ingredientList;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientListId
        {
            get
            {
                return _IngredientListId;
            }
            set
            {
                if (_IngredientListId != value)
                {
                    OnIngredientListIdChanging(value);
                    ReportPropertyChanging("IngredientListId");
                    _IngredientListId = StructuralObject.SetValidValue(value, "IngredientListId");
                    ReportPropertyChanged("IngredientListId");
                    OnIngredientListIdChanged();
                }
            }
        }
        private global::System.Int32 _IngredientListId;
        partial void OnIngredientListIdChanging(global::System.Int32 value);
        partial void OnIngredientListIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientId
        {
            get
            {
                return _IngredientId;
            }
            set
            {
                OnIngredientIdChanging(value);
                ReportPropertyChanging("IngredientId");
                _IngredientId = StructuralObject.SetValidValue(value, "IngredientId");
                ReportPropertyChanged("IngredientId");
                OnIngredientIdChanged();
            }
        }
        private global::System.Int32 _IngredientId;
        partial void OnIngredientIdChanging(global::System.Int32 value);
        partial void OnIngredientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value, "Amount");
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Int32 _Amount;
        partial void OnAmountChanging(global::System.Int32 value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MeasurementId
        {
            get
            {
                return _MeasurementId;
            }
            set
            {
                OnMeasurementIdChanging(value);
                ReportPropertyChanging("MeasurementId");
                _MeasurementId = StructuralObject.SetValidValue(value, "MeasurementId");
                ReportPropertyChanged("MeasurementId");
                OnMeasurementIdChanged();
            }
        }
        private global::System.Int32 _MeasurementId;
        partial void OnMeasurementIdChanging(global::System.Int32 value);
        partial void OnMeasurementIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                OnRecipeIdChanging(value);
                ReportPropertyChanging("RecipeId");
                _RecipeId = StructuralObject.SetValidValue(value, "RecipeId");
                ReportPropertyChanged("RecipeId");
                OnRecipeIdChanged();
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_IngredientList_Ingredient", "Ingredient")]
        public Ingredient Ingredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Ingredient", "Ingredient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Ingredient", "Ingredient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ingredient> IngredientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Ingredient", "Ingredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ingredient>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Ingredient", "Ingredient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_IngredientList_Measurement", "Measurement")]
        public Measurement Measurement
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measurement>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Measurement", "Measurement").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measurement>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Measurement", "Measurement").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Measurement> MeasurementReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measurement>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Measurement", "Measurement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Measurement>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Measurement", "Measurement", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_IngredientList_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Recipe", "Recipe", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db505e4eb8d47b40b7a6d7a05a001ba2a9Model", Name="Measurement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Measurement : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Measurement object.
        /// </summary>
        /// <param name="measurementId">Initial value of the MeasurementId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Measurement CreateMeasurement(global::System.Int32 measurementId, global::System.String name)
        {
            Measurement measurement = new Measurement();
            measurement.MeasurementId = measurementId;
            measurement.Name = name;
            return measurement;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MeasurementId
        {
            get
            {
                return _MeasurementId;
            }
            set
            {
                if (_MeasurementId != value)
                {
                    OnMeasurementIdChanging(value);
                    ReportPropertyChanging("MeasurementId");
                    _MeasurementId = StructuralObject.SetValidValue(value, "MeasurementId");
                    ReportPropertyChanged("MeasurementId");
                    OnMeasurementIdChanged();
                }
            }
        }
        private global::System.Int32 _MeasurementId;
        partial void OnMeasurementIdChanging(global::System.Int32 value);
        partial void OnMeasurementIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_IngredientList_Measurement", "IngredientList")]
        public EntityCollection<IngredientList> IngredientLists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<IngredientList>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Measurement", "IngredientList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<IngredientList>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Measurement", "IngredientList", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db505e4eb8d47b40b7a6d7a05a001ba2a9Model", Name="Recipe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recipe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Recipe object.
        /// </summary>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Recipe CreateRecipe(global::System.Int32 recipeId, global::System.String name)
        {
            Recipe recipe = new Recipe();
            recipe.RecipeId = recipeId;
            recipe.Name = name;
            return recipe;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                if (_RecipeId != value)
                {
                    OnRecipeIdChanging(value);
                    ReportPropertyChanging("RecipeId");
                    _RecipeId = StructuralObject.SetValidValue(value, "RecipeId");
                    ReportPropertyChanged("RecipeId");
                    OnRecipeIdChanged();
                }
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_IngredientList_Recipe", "IngredientList")]
        public EntityCollection<IngredientList> IngredientLists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<IngredientList>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Recipe", "IngredientList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<IngredientList>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_IngredientList_Recipe", "IngredientList", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db505e4eb8d47b40b7a6d7a05a001ba2a9Model", "FK_Directions_Recipe", "Direction")]
        public EntityCollection<Direction> Directions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Direction>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_Directions_Recipe", "Direction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Direction>("db505e4eb8d47b40b7a6d7a05a001ba2a9Model.FK_Directions_Recipe", "Direction", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
